# Generated by Django 4.1.2 on 2022-10-04 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIP', models.CharField(max_length=9)),
                ('Nama', models.TextField()),
                ('Tanggallahir', models.TextField()),
                ('Photo', models.TextField()),
                ('Email', models.TextField()),
                ('Fakultas', models.TextField()),
                ('Prodi', models.TextField()),
                ('Alamatrumah', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='index',
            name='Dosen_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='faperta.dosen'),
            preserve_default=False,
        ),
    ]
