# Generated by Django 4.1.2 on 2022-10-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0002_dosen_index_dosen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='Dosen_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faperta.dosen'),
        ),
    ]
